
 http://localhost:5000/status

###

 http://localhost:5000/admin/login
 Authorization: Basic YmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldDpTdGRiZHR5aDIh

###

 http://localhost:5000/instructor/login
 Authorization: Basic YmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldDpTdGRiZHR5aDIh

###

 http://localhost:5000/student/login
 Authorization: Basic YmVzZUBnbWFpbC5jb206U3RkYmR0eWgyIQ==

###
http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmRhZjQ3Y2Y1MmVmZDA2MTY1OWI4YSIsImVtYWlsIjoiYmVzZUBnbWFpbC5jb20iLCJTdHVkZW50SUQiOiJFVFMwMTIzLzEyIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE3MTEzODg5MTAsImV4cCI6MTcxMTM5NjExMH0.hSxBTC-TIIp6-uFqM6o8kdS81mSW8PYax_4XUhD5r1c

###

 http://localhost:5000/logout
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmIzOGU1YzVkMmM0MzE4Yzg3YjM0MCIsImVtYWlsIjoiYmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldCIsIm5hbWUiOiJCZXN1ZmthZCBZaWxtYSIsImlhdCI6MTcxMDk2ODg0NSwiZXhwIjoxNzEwOTcwNjQ1fQ.3naBtkScdxbe5FkvUDN0wAoGRffuZXq9rFN-A2flB4k

###

http://localhost:/500/admin/registerStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmIzOGU1YzVkMmM0MzE4Yzg3YjM0MCIsImVtYWlsIjoiYmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldCIsIm5hbWUiOiJCZXN1ZmthZCBZaWxtYSIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTcxMTAwODQ3NiwiZXhwIjoxNzExMDEwMjc2fQ.EgBjNzuaroH_Gdnc_VWgo2wdXmRvDxC3YfRGCPEarrY
Content-Type: application/json
{
    "student": {
        "name": "Abebe bela",
        "email": "email1",
        "password": "pass",
        "age": 23,
        "phone": 0,
        "type": "student",
        "dept": "electrical",
        "batch": "2016 graduate",
        "StudentID": "ETS0123/12",
        "registered": false,
    }
}


###

#  curl -XPOST http://localhost:5000/admin/create/student -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmIzOGU1YzVkMmM0MzE4Yzg3YjM0MCIsImVtYWlsIjoiYmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldCIsIm5hbWUiOiJCZXN1ZmthZCBZaWxtYSIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTcxMTExNTQzNiwiZXhwIjoxNzExMTE3MjM2fQ.k6VqwGcxonnCFu-6_A503B5ff2Jt-X3tDIDJnbRhmkI" -H "Content-Type: application/json" -d '{"student": {"email": "bese@gmail.com", "name": "Besufikad Yilma", "dept": "Electrical & Computer Engineering", "batch": "2016 graduate", "StudentID": "ETS0123/12", "registered": true, "password": "password21", "age": 19, "phone": 0, "type": "student"}}' -v