
 http://localhost:5000/status

###

 http://localhost:5000/admin/login
 Authorization: Basic YmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldDpTdGRiZHR5aDIh

###

 http://localhost:5000/instructor/login
 Authorization: Basic YmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldDpTdGRiZHR5aDIh

###

 http://localhost:5000/student/login
 Authorization: Basic YmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldDpTdGRiZHR5aDIh


###

 http://localhost:5000/logout
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmIzOGU1YzVkMmM0MzE4Yzg3YjM0MCIsImVtYWlsIjoiYmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldCIsIm5hbWUiOiJCZXN1ZmthZCBZaWxtYSIsImlhdCI6MTcxMDk2ODg0NSwiZXhwIjoxNzEwOTcwNjQ1fQ.3naBtkScdxbe5FkvUDN0wAoGRffuZXq9rFN-A2flB4k

###

http://localhost:/500/admin/registerStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmIzOGU1YzVkMmM0MzE4Yzg3YjM0MCIsImVtYWlsIjoiYmVzdWZrYWQueWlsbWFAYWFzdHVzdHVkZW50LmVkdS5ldCIsIm5hbWUiOiJCZXN1ZmthZCBZaWxtYSIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTcxMTAwODQ3NiwiZXhwIjoxNzExMDEwMjc2fQ.EgBjNzuaroH_Gdnc_VWgo2wdXmRvDxC3YfRGCPEarrY
Content-Type: application/json
{
    "student": {
        "name": "Abebe bela",
        "email": "email1",
        "password": "pass",
        "age": 23,
        "phone": 0,
        "type": "student",
        "dept": "electrical",
        "batch": "2016 graduate",
        "StudentID": "ETS0123/12",
        "registered": false,
    }
}